#!/bin/sh
apt-get install -y software-properties-common
add-apt-repository -y ppa:kevinkreiser/prime-server
apt-get update -o Dir::Etc::sourcelist="sources.list.d/kevinkreiser-prime-server-$(lsb_release -c -s).list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
